Parameters:
  ServiceName:
    Description: "Name of service the stack would be used for: "
    Type: String 
  InstanceType:
    Description: "EC2 type to be launched: Permitted types: t2.micro, m1.small, m1.large"
    Type: String 
    Default: t2.micro 
    AllowedValues:
    - t2.micro
    - m1.small 
    - m1.large 
  KeyName:
    Description: "KeyPair file name for remote login"
    Type: AWS::EC2::KeyPair::KeyName
Mappings: 
  RegionAMI:
    us-east-1:
      AMI: ami-08f3d892de259504d
    eu-west-1:
      AMI: ami-0c3e74fa87d2a4227
    ap-south-1:
      AMI: ami-0732b62d310b80e97
Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: 
        Fn::FindInMap: 
        - RegionAMI
        - !Ref AWS::Region 
        - AMI
      Tags:
      - Key: "Name"
        Value: !Ref ServiceName 
      KeyName: !Ref KeyName
      SecurityGroups: 
      - !Ref JumpBoxSG
  JumpBoxSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Open port 22 for ssh connections 
      SecurityGroupIngress: 
      - IpProtocol: tcp 
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
