Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08f3d892de259504d #Linux ami id in us-east region
      Tags:
      - Key: Name
        Value: jump box
