Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08f3d892de259504d #Linux ami id in us-east region
      Tags:
      - Key: "Name"
        Value: !Join 
        - "" 
        - - "Jump Box for "
          - !Ref AWS::Region
      SecurityGroups: 
      - !Ref MySecurityGroup
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Open port 22 for ssh connections 
      SecurityGroupIngress: 
      - IpProtocol: tcp 
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
